#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

UPSTREAM_BRANCH=`git for-each-ref --format='%(upstream:short)' $(git symbolic-ref -q HEAD)`
BASE_BRANCH="origin/master"
TARGET_BRANCH=${UPSTREAM_BRANCH:-$BASE_BRANCH}

codeStyleCheckByProjectType() {
  case $1 in
    api)
      local DIFF_FILES=$(git diff $2 --name-only | grep "api-server")
      if [ -n "$DIFF_FILES" ]; then
        yarn api:format
      fi
      ;;
    ui)
      local DIFF_FILES=$(git diff $2 --name-only | grep "front-ui")
      if [ -n "$DIFF_FILES" ]; then
        yarn ui:format
      fi
      ;;
    *)
      echo "Skip>> Invalid project type: $1"
      ;;
  esac
}

codeStyleCheckByProjectType api $TARGET_BRANCH
codeStyleCheckByProjectType ui $TARGET_BRANCH
